language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
